#!/bin/sh

# From i3blocks
cpu_load(){
    idle=$(mpstat 1 1 | sed -n 's/^Average.* \([0-9]\+\.[0-9]\+\)/\1/p')
    echo "100-${idle}" | bc -l
}

cpu_load=$(cpu_load)
load="$(printf ' %6.2f%% ' ${cpu_load})"

if [ ${cpu_load%.*} -ge 80 ]
then
    echo "<span color='OrangeRed'>${load}</span>"
    exit
fi
if [ ${cpu_load%.*} -ge 50 ]
then
    echo "<span color='yellow'>${load}</span>"
    exit
fi

echo "${load}"
