#!/bin/sh

up(){
    ping -W 1 -c 1 ${1} >/dev/null 2>&1
}

# cloudflare, opendns & google
if ! up 1.1.1.1 && ! up 208.67.222.222 && ! up 8.8.8.8
then
    echo "<span color='OrangeRed'>*</span>"
    exit 1
fi

echo "<span color='green'>@</span>"
