#!/usr/bin/env bash

# set -x

pid=${$}

# kills all other instances
pgrep -f autolock | grep -v ${pid} | xargs -r kill -9

while true
do
    sleep 300
    if ! pgrep i3lock 2>&1 >/dev/null
    then
        idle=$(xprintidle)
        if [[ ${idle} -gt 290000 ]]
        then
            ~/.i3/scripts/lock
        fi
    fi
done
