#!/bin/sh

# Terminating all instances of the graphical emacs client
pkill -f 'emacsclient -c'

# Terminating all instances of vim and neovim that may be open in a tmux session
pkill vim

# Terminating all instances of the X Virtual Frame Buffer
pkill Xvfb

# Terminating all instances of the X11 VNC Server
pkill x11vnc

# Terminating all instances of the ssh client
pkill '\bssh\b'

# Terminating pulseaudio (and allow applications to start it on demand)
pkill pulseaudio

# Starting mpd (Music Player Daemon) & mpdscribble (Libre.fm & Last.fm scrobbler)
[ -x "$(command -v mpd)" ] && [ ! -s ~/.config/mpd/pid ] && mpd
[ -x "$(command -v mpdscribble)" ] && \
    [ -s ~/.config/mpd/pid ] && [ ! -s ~/.mpdscribble/pid ] && mpdscribble

# Starting udevil's devmon
[ -x "$(command -v devmon)" ] && pgrep -f '/bin/bash /usr/bin/devmon' || \
    devmon 2>&1 >/dev/null &

# Starting espanso (Cross-platform Text Expander written in Rust)
[ -x "$(command -v espanso)" ] && espanso restart

# Sourcing ~/.profile if it exists
[ -f ~/.profile ] && source ~/.profile

# Sourcing a local script if it exists
[ -x ~/.local/share/wm/scripts/login.local ] && ~/.local/share/wm/scripts/login.local
