#!/usr/bin/env bash

# set -x
set -e

print_usage() {
	printf '\n%s\n' "$(basename $0) FILE"
}

if [[ ! ${#} -eq 1 ]]
then
	print_usage 1>&2
	exit 1
fi

file="${1}"
destination=~/.local/share/wallpaper

! [[ -d "${destination}" ]] && mkdir -p "${destination}"

cp -f "${file}" "${destination}"

name="${file##*/}"

ln -sf "${destination}/${name}" "${destination}"/current

hsetroot -cover "${destination}"/current
