#!/bin/sh

# set -x

print_usage() {
	printf '\n%s\n' "$(basename "${0}") [-d] [-l] [-c PATH] -- [ARGS...]"
}

path=""
background="-u" # light by default
while getopts ":c:dlh" opt
do
    case ${opt} in
        c)
            path="${OPTARG}"
            ;;
        d)
            background=""
            ;;
        l)
            background="-u"
            ;;
        h)
            print_usage
            exit 0
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

if [ -n "${path}" ]
then
    cd "${path}"
fi

/usr/local/bin/st ${background} -f "Iosevka:size=12" "${@}" >/dev/null 2>&1 &
