-- local home = os.getenv("MPV_CONFIG_HOME")
--
-- if not home or home == "" then
--   print("MPV_CONFIG_HOME is required.")
--   return
-- end
--
-- local concat = table.concat
--
-- package.path = concat({ package.path, concat({ home, "lib/?.lua" }, "/") }, ";")
--
-- local utils = require("utils")
--
-- local file_loaded, file_loaded_cb
--
-- file_loaded_cb = function()
--   if not utils.is_file_loaded() then return end
--
--   print("Index now")
--
--   mp.unregister_event(file_loaded_cb)
-- end
--
-- mp.register_event("file-loaded", file_loaded_cb)
