#!/bin/sh

# set -x

date_and_time(){
    date '+%b %e %a %_Hh%M'
}

format_cpu_load(){
    printf '%6.2f%%\n' ${1}
}

# From i3blocks
cpu_load(){
    idle=$(mpstat 1 1 | sed -n 's/^Average.* \([0-9]\+\.[0-9]\+\)/\1/p')
    load=$(echo "100-${idle}" | bc -l)
    if [ -n "${load%.*}" ] && [ ${load%.*} -gt 80 ]
    then
        echo "<span color='red'>$(format_cpu_load ${load})</span>"
        exit
    fi
    if [ -n "${load%.*}" ] && [ ${load%.*} -gt 50 ]
    then
        echo "<span color='yellow'>$(format_cpu_load ${load})</span>"
        exit
    fi
    format_cpu_load ${load}
}

# From i3blocks
memory_info(){
    type=${1}
    awk -v type=$type '
    /^MemFree:/ {
        mem_free=$2
    }
    /^Buffers:/ {
        mem_free+=$2
    }
    /^Cached:/ {
        mem_free+=$2
    }
    /^SwapTotal:/ {
        swap_total=$2
    }
    /^SwapFree:/ {
        swap_free=$2
    }
    END {
        # full text
        if (type == "swap")
            printf("%4.1fG\n", (swap_total-swap_free)/1024/1024)
        else
            printf("%4.1fG\n", mem_free/1024/1024)
    }
    ' /proc/meminfo
}

# From i3blocks
hdd_info(){
    df -h -P -l / | awk '/^\// {print $4}'
}

internet1(){
    ping -W 1 -c 1 1.1.1 >/dev/null 2>&1 # cloudflare
}

internet2(){
    ping -W 1 -c 1 208.67.222.222 >/dev/null 2>&1 # opendns
}

internet3(){
    ping -W 1 -c 1 8.8.8.8 >/dev/null 2>&1 # google
}

internet(){
    if ! internet1 && ! internet2 && ! internet3
    then
        echo "<span color='yellow'>*</span>"
        exit
    fi
    echo "<span color='#89CFF0'>@</span>"
}

# Killing all other instances
pid=${$}
pgrep -f '/bin/sh .*\.local/share/dwm/scripts/dwm_status$' \
    | grep -v ${pid} | xargs -r kill -9

status=""

while true
do
    seconds=$(date '+%-S')

    if [ $((seconds%60)) -eq 0 ]
    then
        # If there is no X session, then die
        xset q 2>&1 >/dev/null || exit 1
    fi

    ([ -z "${status}" ] || [ $((seconds%10)) -eq 0 ]) && internet="$(internet)"
    ([ -z "${status}" ] || [ $((seconds%20)) -eq 0 ]) && hdd_info=$(hdd_info)
    ([ -z "${status}" ] || [ $((seconds%10)) -eq 0 ]) && memory_info="$(memory_info)"
    ([ -z "${status}" ] || [ $((seconds%5))  -eq 0 ]) && cpu_load="$(cpu_load)"
    ([ -z "${status}" ] || [ $((seconds%60)) -eq 0 ]) && date_and_time="$(date_and_time)"
    status="$(printf ' %s  [%6s]  %5s  %s  %s ' \
       "${internet}" ${hdd_info} "${memory_info}" "${cpu_load}" "${date_and_time}")"
    xsetroot -name "${status}"
    sleep 4
done
