#!/bin/sh

# set -x

date_and_time(){
    date '+%Y %b %e %a %Hh%M'
}

# From i3blocks
cpu_usage(){
    idle=$(mpstat 1 1 | sed -n 's/^Average.* \([0-9]\+\.[0-9]\+\)/\1/p')
    usage="$(echo "100-${idle}"|bc -l)"
    echo ${usage}
}

# From i3blocks
memory_info(){
    type=${1}
    awk -v type=$type '
    /^MemFree:/ {
        mem_free=$2
    }
    /^Buffers:/ {
        mem_free+=$2
    }
    /^Cached:/ {
        mem_free+=$2
    }
    /^SwapTotal:/ {
        swap_total=$2
    }
    /^SwapFree:/ {
        swap_free=$2
    }
    END {
        # full text
        if (type == "swap")
            printf("%4.1fG\n", (swap_total-swap_free)/1024/1024)
        else
            printf("%4.1fG\n", mem_free/1024/1024)
    }
    ' /proc/meminfo
}

# From i3blocks
hdd_info(){
    df -h -P -l / | awk '/^\// {print $4}'
}

internet1(){
    ping -W 1 -c 1 8.8.8.8 >/dev/null 2>&1 # google's dns
}

internet2(){
    ping -W 1 -c 1 208.67.222.222 >/dev/null 2>&1 # opendns
}

internet(){
    if ! internet1 && ! internet2
    then
        echo "NO INTERNET"
        exit
    fi

    echo OK
}

while true
do
    date_and_time="$(date_and_time)"
    cpu_usage=$(cpu_usage)
    memory_info="$(memory_info)"
    hdd_info=$(hdd_info)
    internet="$(internet)"
    status="$(printf ' %s   [%5s]   %5s   %6.2f%%   %s ' \
       "${internet}" ${hdd_info} "${memory_info}" ${cpu_usage} "${date_and_time}")"
    xsetroot -name "${status}"
    sleep 9
done
