#!/bin/sh

# set -x

date_and_time(){
    date '+%Y %b %e %a %Hh%M'
}

# From i3blocks
cpu_usage(){
    idle=$(mpstat 1 1 | sed -n 's/^Average.* \([0-9]\+\.[0-9]\+\)/\1/p')
    usage="$(echo "100-${idle}"|bc -l)"
    echo ${usage}
}

# From i3blocks
memory_info(){
    type=${1}
    awk -v type=$type '
    /^MemFree:/ {
        mem_free=$2
    }
    /^Buffers:/ {
        mem_free+=$2
    }
    /^Cached:/ {
        mem_free+=$2
    }
    /^SwapTotal:/ {
        swap_total=$2
    }
    /^SwapFree:/ {
        swap_free=$2
    }
    END {
        # full text
        if (type == "swap")
            printf("%4.1fG\n", (swap_total-swap_free)/1024/1024)
        else
            printf("%4.1fG\n", mem_free/1024/1024)
    }
    ' /proc/meminfo
}

# From i3blocks
hdd_info(){
    df -h -P -l / | awk '/^\// {print $4}'
}

while true
do
    date_and_time="$(date_and_time)"
    cpu_usage=$(cpu_usage)
    memory_info="$(memory_info)"
    hdd_info=$(hdd_info)
    status="$(printf ' HDD %s   RAM %s   CPU %6.2f%%   %s ' \
        ${hdd_info} "${memory_info}" ${cpu_usage} "${date_and_time}")"
    xsetroot -name "${status}"
    sleep 9
done
